# -*- coding: utf-8 -*-
"""easyocr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHgA_7ZK0WkOT0mw-hKnIx-plXpwLYF_
"""

!pip install easyocr

import cv2
import easyocr

reader = easyocr.Reader(['en'])

image = '/content/d3.jpg'
result = reader.readtext(image , allowlist = 'TOPDWN')

# Tanınan metni yazdır
if result:
    for detection in result:
        text = detection
        print("Metin:", text)
        # Koordinatları da yazdırabilirsiniz:
        # print("Koordinatlar:", detection[1])
else:
    print("Metin algılanamadı")