# -*- coding: utf-8 -*-
"""tesseract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16OrSEK8VNlORjE-RUbhNh_4i5u_Tqtqh
"""

!apt install tesseract-ocr
!apt install libtesseract-dev

import cv2
import pytesseract

# Görüntüyü yükle
image = cv2.imread('/content/down.jpg')



# Görüntüyü gri tonlamaya dönüştür
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Metni tanı
text = pytesseract.image_to_string(gray_image)

# Tanınan metni ekrana yazdır
print("Tanınan Metin:", text)